name: Build Android

on: [push, pull_request]

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install Cordova
        run: npm install -g cordova

      - name: Install Ionic
        run: npm install -g @ionic/cli

      - name: Install app dependencies
        run: npm install

      - name: Build the app
        run: npm run build

      - name: Run E2E test
        run: npm run test:e2e-headless  
        
      - name: Sync with source
        run: npx cap sync

      - name: Build Android APK
        working-directory: ./android/
        run: ./gradlew assembleRelease

      - name: Sign app APK 
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: android/app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      - name: Upload Android APK
        uses: actions/upload-artifact@v2
        with:
          name: app-release
          path: android/app/build/outputs/apk/release/app-release-unsigned-signed.apk
      
      - name: Create release
        uses: WebFreak001/deploy-nightly@v1.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: https://uploads.github.com/repos/Umfi/my-fitness-app/releases/42846272/assets{?name,label}
          release_id: 42846272 
          asset_path: android/app/build/outputs/apk/release/app-release-unsigned-signed.apk
          asset_name: myfitnessapp-latest.apk
          asset_content_type: application/zip
